name: caribou_hi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - versioneer
  - numpy
  - pymc>=5
  - pytensor
  - nutpie
  - numba
#  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jaxlib==0.4.28
  - jax==0.4.28
  - blackjax
  - numpyro
  - pip
  - pip:
    - "sphinx_rtd_theme"
    - "nbsphinx"
    - "numpydoc"
    - "bayes_spec>=1.7.4"
    - git+https://github.com/tvwenger/arviz.git@plot_pair_reference_labels